# Generated by Django 5.2.3 on 2025-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees_images/'),
        ),
    ]
